transfer:
  bufferSize: 32768

consistency:
  onConflict: overwrite  # overwrite | backupAndOverwrite

watcher:
  path: /opt/sync-net/

discovery:
  broadcastPort: 9999
  tcpPort: 9000
  broadcastInterval: 1m
  bufferSize: 4096